[[headers]]
  for = "/*"
  [headers.values]
    # Allow loading of unsafe scripts
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "/api/*"
  to = "http://34.201.107.67:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200